CREATE TABLE vouchers (
	id UUID PRIMARY KEY,
	brand_id UUID NOT NULL,
	name VARCHAR(255) NOT NULL,
	cost_in_point INTEGER NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (brand_id) REFERENCES brands (id) ON DELETE CASCADE
);